-- 应用表
CREATE TABLE IF NOT EXISTS sys_apps (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '应用名称',
    code VARCHAR(50) NOT NULL UNIQUE DEFAULT '' COMMENT '应用代码',
    description VARCHAR(200) DEFAULT '' COMMENT '应用描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '删除时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='应用表';

-- 用户应用关联表
CREATE TABLE IF NOT EXISTS sys_user_apps (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    app_id BIGINT UNSIGNED NOT NULL COMMENT '应用ID',
    is_default BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否默认应用',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '删除时间',
    UNIQUE KEY uk_user_app (user_id, app_id) COMMENT '用户应用唯一键',
    FOREIGN KEY (user_id) REFERENCES sys_users(id) ON DELETE CASCADE,
    FOREIGN KEY (app_id) REFERENCES sys_apps(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户应用关联表';

-- 应用模板表
CREATE TABLE IF NOT EXISTS sys_app_templates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '模板名称',
    description VARCHAR(200) DEFAULT '' COMMENT '模板描述',
    configuration JSON NOT NULL COMMENT '模板配置',
    price DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '模板价格',
    creator_id BIGINT UNSIGNED NOT NULL COMMENT '创建者ID',
    downloads INT NOT NULL DEFAULT 0 COMMENT '下载次数',
    status TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0:未上架 1:已上架',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    deleted_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '删除时间',
    FOREIGN KEY (creator_id) REFERENCES sys_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='应用模板表';
