-- 定时任务表
CREATE TABLE IF NOT EXISTS scheduled_tasks (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    application_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL COMMENT 'sql:SQL任务 http:HTTP任务',
    cron VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    timeout INT NOT NULL DEFAULT 60,
    retry_times INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1 COMMENT '0:禁用 1:启用',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 任务执行日志表
CREATE TABLE IF NOT EXISTS task_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    task_id BIGINT UNSIGNED NOT NULL,
    status TINYINT NOT NULL COMMENT '0:失败 1:成功',
    result TEXT,
    error TEXT,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    FOREIGN KEY (task_id) REFERENCES scheduled_tasks(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 元素触发器表
CREATE TABLE IF NOT EXISTS element_triggers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    application_id BIGINT UNSIGNED NOT NULL,
    element_type VARCHAR(20) NOT NULL COMMENT 'form:表单 model:数据模型',
    element_id BIGINT UNSIGNED NOT NULL,
    trigger_point VARCHAR(20) NOT NULL COMMENT 'before:之前 after:之后',
    type VARCHAR(20) NOT NULL COMMENT 'sql:SQL任务 http:HTTP任务',
    content TEXT NOT NULL,
    status TINYINT NOT NULL DEFAULT 1 COMMENT '0:禁用 1:启用',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
