-- 数据表配置
CREATE TABLE IF NOT EXISTS config_table (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    app_id BIGINT UNSIGNED NOT NULL COMMENT '应用ID',
    table_name VARCHAR(64) NOT NULL COMMENT '表名',
    display_name VARCHAR(64) NOT NULL COMMENT '显示名称',
    description TEXT COMMENT '描述',
    filters JSON COMMENT '筛选配置项，包含列名和类型(time/other)',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    UNIQUE KEY uk_app_table (app_id, table_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据表配置';

-- 维度配置
CREATE TABLE IF NOT EXISTS config_dimension (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    app_id BIGINT UNSIGNED NOT NULL COMMENT '应用ID',
    table_name VARCHAR(64) NOT NULL COMMENT '维度表名',
    display_name VARCHAR(64) NOT NULL COMMENT '显示名称',
    description TEXT COMMENT '描述',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    UNIQUE KEY uk_app_dimension (app_id, table_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='维度配置';

-- 数据模型配置
CREATE TABLE IF NOT EXISTS config_model (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    app_id BIGINT UNSIGNED NOT NULL COMMENT '应用ID',
    model_name VARCHAR(64) NOT NULL COMMENT '模型名称',
    display_name VARCHAR(64) NOT NULL COMMENT '显示名称',
    description TEXT COMMENT '描述',
    configuration JSON COMMENT '模型配置，包含表关系、关联字段等',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    UNIQUE KEY uk_app_model (app_id, model_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据模型配置';

-- 表单配置
CREATE TABLE IF NOT EXISTS config_form (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    app_id BIGINT UNSIGNED NOT NULL COMMENT '应用ID',
    model_id BIGINT UNSIGNED NOT NULL COMMENT '关联的数据模型ID',
    form_name VARCHAR(64) NOT NULL COMMENT '表单名称',
    display_name VARCHAR(64) NOT NULL COMMENT '显示名称',
    description TEXT COMMENT '描述',
    configuration JSON COMMENT '表单配置，包含元素类型、布局等',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    UNIQUE KEY uk_app_form (app_id, form_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='表单配置';

-- 菜单配置
CREATE TABLE IF NOT EXISTS config_menu (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    app_id BIGINT UNSIGNED NOT NULL COMMENT '应用ID',
    node_id VARCHAR(32) NOT NULL COMMENT '节点ID',
    parent_id VARCHAR(32) NOT NULL DEFAULT '0' COMMENT '父节点ID',
    menu_name VARCHAR(64) NOT NULL COMMENT '菜单名称',
    menu_code VARCHAR(64) NOT NULL COMMENT '菜单编码',
    menu_type TINYINT NOT NULL COMMENT '菜单类型：1目录 2菜单 3按钮',
    level INT NOT NULL DEFAULT 1 COMMENT '层级',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    icon VARCHAR(64) COMMENT '图标',
    path VARCHAR(255) COMMENT '路由路径',
    component VARCHAR(255) COMMENT '前端组件',
    permission VARCHAR(255) COMMENT '权限标识',
    visible TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否可见',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    UNIQUE KEY uk_app_menu (app_id, node_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单配置';
