-- 应用表
CREATE TABLE IF NOT EXISTS sys_apps (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '应用名称',
    code VARCHAR(50) NOT NULL UNIQUE DEFAULT '' COMMENT '应用代码',
    description VARCHAR(200) DEFAULT '' COMMENT '应用描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='应用表';