-- 数据表配置
CREATE TABLE IF NOT EXISTS sys_config_tables (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    app_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '应用ID',
    table_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '表名',
    display_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '显示名称',
    description VARCHAR(200) DEFAULT '' COMMENT '描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    UNIQUE KEY uk_app_table (app_id, table_name) COMMENT '应用ID和表名唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据表配置' COLLATE=utf8mb4_general_ci;

-- 维度配置
CREATE TABLE IF NOT EXISTS sys_config_dimensions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    app_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '应用ID',
    table_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '维度表名',
    display_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '显示名称',
    description VARCHAR(200) DEFAULT '' COMMENT '描述',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    UNIQUE KEY uk_app_dimension (app_id, table_name) COMMENT '应用ID和维度表名唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='维度配置' COLLATE=utf8mb4_general_ci;

-- 数据模型配置
CREATE TABLE IF NOT EXISTS sys_config_models (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    app_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '应用ID',
    model_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '模型名称',
    display_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '显示名称',
    description VARCHAR(200) DEFAULT '' COMMENT '描述',
    configuration JSON COMMENT '模型配置，包含表关系、关联字段等',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    UNIQUE KEY uk_app_model (app_id, model_name) COMMENT '应用ID和模型名称唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据模型配置' COLLATE=utf8mb4_general_ci;

-- 表单配置
CREATE TABLE IF NOT EXISTS sys_config_forms (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    app_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '应用ID',
    model_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '关联的数据模型ID',
    form_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '表单名称',
    form_type VARCHAR(20) NOT NULL DEFAULT '' COMMENT '表单类型：form/table/chart/dashboard',
    display_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '显示名称',
    description VARCHAR(200) DEFAULT '' COMMENT '描述',
    configuration JSON COMMENT '表单配置，包含元素类型、布局等',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    -- deleted_at DATETIME NULL DEFAULT '1901-01-01 00:00:00' COMMENT '删除时间',
    UNIQUE KEY uk_app_form (app_id, form_name) COMMENT '应用ID和表单名称唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='表单配置' COLLATE=utf8mb4_general_ci;

-- 菜单配置
CREATE TABLE IF NOT EXISTS sys_config_menus (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    app_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '应用ID',
    node_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '节点ID',
    parent_id VARCHAR(32) NOT NULL DEFAULT '0' COMMENT '父节点ID',
    menu_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '菜单名称',
    menu_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT '菜单编码',
    menu_type TINYINT NOT NULL DEFAULT 1 COMMENT '菜单类型：1目录 2菜单 3按钮',
    level INT NOT NULL DEFAULT 1 COMMENT '层级',
    sort INT NOT NULL DEFAULT 0 COMMENT '排序',
    icon VARCHAR(64) DEFAULT '' COMMENT '图标',
    path VARCHAR(255) DEFAULT '' COMMENT '路由路径',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '是否可见',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    UNIQUE KEY uk_app_menu (app_id, node_id) COMMENT '应用ID和节点ID唯一索引'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='菜单配置' COLLATE=utf8mb4_general_ci;

-- 配置版本记录
CREATE TABLE IF NOT EXISTS sys_config_versions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    app_id BIGINT UNSIGNED NOT NULL COMMENT '应用ID',
    config_type VARCHAR(20) NOT NULL COMMENT '配置类型：table, dimension, model, form_',
    config_id BIGINT UNSIGNED NOT NULL COMMENT '配置ID',
    version INT NOT NULL DEFAULT 1 COMMENT '版本号',
    comment VARCHAR(255) DEFAULT '' COMMENT '版本说明',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='配置版本记录' COLLATE=utf8mb4_general_ci;