-- 用户表
CREATE TABLE IF NOT EXISTS sys_users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
    username VARCHAR(50) NOT NULL DEFAULT '' UNIQUE COMMENT '用户名',
    nickname VARCHAR(50) NOT NULL DEFAULT '' COMMENT '昵称',
    avatar VARCHAR(255) NOT NULL DEFAULT '' COMMENT '头像',
    password VARCHAR(255) NOT NULL DEFAULT '' COMMENT '密码',
    email VARCHAR(100) DEFAULT '' COMMENT '电子邮件',
    phone VARCHAR(20) DEFAULT '' COMMENT '电话',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    deleted_at DATETIME NULL DEFAULT '1901-01-01 00:00:00' COMMENT '删除时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户表';

-- 角色表
CREATE TABLE IF NOT EXISTS sys_roles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '角色ID',
    name VARCHAR(50) NOT NULL DEFAULT '' COMMENT '角色名称',
    code VARCHAR(50) NOT NULL DEFAULT '' UNIQUE COMMENT '角色代码',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    deleted_at DATETIME NULL DEFAULT '1901-01-01 00:00:00' COMMENT '删除时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色表';

-- 权限表
CREATE TABLE IF NOT EXISTS sys_permissions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '权限ID',
    name VARCHAR(50) NOT NULL DEFAULT '' COMMENT '权限名称',
    code VARCHAR(50) NOT NULL DEFAULT '' UNIQUE COMMENT '权限代码',
    type VARCHAR(20) NOT NULL DEFAULT '' COMMENT '类型 menu:菜单 api:接口',
    path VARCHAR(255) DEFAULT '' COMMENT '路径',
    method VARCHAR(10) DEFAULT '' COMMENT '方法',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '状态 0:禁用 1:启用',
    description VARCHAR(200) DEFAULT '' COMMENT '描述',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    updater_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '更新人ID',
    deleted_at DATETIME NULL DEFAULT '1901-01-01 00:00:00' COMMENT '删除时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='权限表';

-- 用户角色关联表
CREATE TABLE IF NOT EXISTS sys_user_roles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '用户角色关联ID',
    user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID',
    role_id BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    UNIQUE KEY uk_user_role (user_id, role_id) COMMENT '唯一键 用户ID和角色ID',
    FOREIGN KEY (user_id) REFERENCES sys_users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES sys_roles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='用户角色关联表';

-- 角色权限关联表
CREATE TABLE IF NOT EXISTS sys_role_permissions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY COMMENT '角色权限关联ID',
    role_id BIGINT UNSIGNED NOT NULL COMMENT '角色ID',
    permission_id BIGINT UNSIGNED NOT NULL COMMENT '权限ID',
    created_at DATETIME NOT NULL DEFAULT '1901-01-01 00:00:00' COMMENT '创建时间',
    creator_id BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '创建人ID',
    UNIQUE KEY uk_role_permission (role_id, permission_id) COMMENT '唯一键 角色ID和权限ID',
    FOREIGN KEY (role_id) REFERENCES sys_roles(id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES sys_permissions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='角色权限关联表';
